server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: root
    password: secret
    change-log: classpath:db/changelog-master.xml