server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  auth-server-url: http://localhost:9999/auth
  realm: SpringBootKeycloak
  resource: my_client_id
  public-client: true
  bearer-only: true